using System.Diagnostics;
using System.IO;
using DuckGame;


namespace DisplayImages
{
    public class PythonAPI  // closed Project since it only works with Diagnostics in the Game, wich need the whole Python311 folder(300mb+) to function
    {
        public static void SliceImageScript(string imageName, string path, string grid)
        {
            ProcessStartInfo start = new ProcessStartInfo();
            //python interprater location
            start.FileName = path + "/Python311/python.exe";
            //argument with file name and input parameters
            start.Arguments = string.Format("{0} {1} {2} {3}", path +"/DisplayImages/imageSlicer.py", imageName, path, grid);
            start.UseShellExecute = false; // dont use OS shell
            start.CreateNoWindow = true;   // no need for extra window
            start.RedirectStandardOutput = true;// Any output, generated by application will be redirected back, since we dont it
            start.RedirectStandardError = true; // Any error in standard output will be redirected back (for example exceptions)
            start.LoadUserProfile = true;

            using (Process process = Process.Start(start))
            {
                using (StreamReader reader = process.StandardOutput)
                {
                    string exception = process.StandardError.ReadToEnd(); // Here are the exceptions from our Python script
                    string result = reader.ReadToEnd(); // Here is the result of StdOut(for example: print "test")

                    if (exception != "")
                    {
                        StreamWriter write = new StreamWriter(path + "/DisplayImages/error.txt");
                        DevConsole.Log(DCSection.Mod, "|RED| something went wrong. Check error.txt for more details");
                        write.WriteLine(exception);
                        write.Close();
                    }
                }
            }
        }
        public static void ResizeImageScript(string imageName, string path, string size)
        {
            ProcessStartInfo start = new ProcessStartInfo(); 
            start.FileName = path + "/Python311/python.exe";
            
            start.Arguments = string.Format("{0} {1} {2} {3}", path + "/DisplayImages/imageResizer.py", imageName, path, size);
            start.UseShellExecute = false;
            start.CreateNoWindow = true;  
            start.RedirectStandardOutput = true;
            start.RedirectStandardError = true; 
            start.LoadUserProfile = true;

            using (Process process = Process.Start(start))
            {
                using (StreamReader reader = process.StandardOutput)
                {
                    string exception = process.StandardError.ReadToEnd();      // for Exceptions
                    string result = reader.ReadToEnd();                        // for return value

                    if (exception != "")
                    {
                        StreamWriter write = new StreamWriter(path + "/DisplayImages/error.txt");
                        DevConsole.Log(DCSection.Mod, "|RED| something went wrong. Check error.txt for more details");
                        write.WriteLine(exception);
                        write.Close();
                    }
                }
            }
        }
    }
}
